### ISSUE TITLE
MemoryError in sampling process (gen_model in generate_caps.py)

### ISSUE THREAD

**Issue by F0Z** [kelvinxu/arctic-captions#12]
My system configuration is i5-4440k with a 4GB GTX 960. When I run the generate_caps.py for the flickr30k version, I get an error like this:
```python
loading data ...
Error when trying to find the memory information on the GPU: initialization error
Error allocating 4000000 bytes of device memory (initialization error). Driver report 0 bytes free and 0 bytes total 
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "generate_caps.py", line 30, in gen_model
    tparams = init_tparams(params)
  File "/home/f0z/sat/arctic-captions/capgen.py", line 94, in init_tparams
    k2 = theano.shared(params[params.keys()[0]], name=params.keys()[0], borrow=True)
  File "/home/f0z/pyenvs/DL/local/lib/python2.7/site-packages/theano/compile/sharedvalue.py", line 208, in shared
    allow_downcast=allow_downcast, **kwargs)
  File "/home/f0z/pyenvs/DL/local/lib/python2.7/site-packages/theano/sandbox/cuda/var.py", line 203, in float32_shared_constructor
    deviceval = type_support_filter(value, type.broadcastable, False, None)
MemoryError: ('Error allocating 4000000 bytes of device memory (initialization error).', "you might consider using 'theano.shared(..., borrow=True)'")
```

I've run ```nvidia-smi``` and there is plenty of memory (~3.5GB and I'm only loading the dev dataset). Also there are no permission issues. Since the error is in declaring shared variables in the gpu through a process, I'm guessing this is due to inability of the function gen_model to allocate memory in GPU from a process. Can anyone please suggest any workarounds?

**Comment by F0Z** [comment]
BTW, this is what I used to build the model.npz.pkl for the model argument -
```python
import capgen as cp
import numpy as np
import cPickle as c
from collections import OrderedDict
import theano

options = {'dim_word':100,  # word vector dimensionality
          'ctx_dim':512,  # context vector dimensionality
          'dim':1000,  # the number of LSTM units
          'attn_type':'stochastic',  # [see section 4 from paper]
          'n_layers_att':1,  # number of layers used to compute the attention weights
          'n_layers_out':1,  # number of layers used to compute logit
          'n_layers_lstm':1,  # number of lstm layers
          'n_layers_init':1,  # number of layers to initialize LSTM at time 0
          'lstm_encoder':False,  # if True, run bidirectional LSTM on input units
          'prev2out':False,  # Feed previous word into logit
          'ctx2out':False,  # Feed attention weighted ctx into logit
          'alpha_entropy_c':0.002,  # hard attn param
          'RL_sumCost':True,  # hard attn param
          'semi_sampling_p':0.5,  # hard attn param
          'temperature':1.,  # hard attn param
          'patience':10,
          'max_epochs':5000,
          'dispFreq':100,
          'decay_c':0.,  # weight decay coeff
          'alpha_c':0.,  # doubly stochastic coeff
          'lrate':0.01,  # used only for SGD
          'selector':False,  # selector (see paper)
          'n_words':10000,  # vocab size
          'maxlen':100,  # maximum length of the description
          'optimizer':'adam',
          'batch_size ': 16,
          'valid_batch_size ': 16,
          'saveto':'model.npz',  # relative path of saved model file
          'validFreq':1000,
          'saveFreq':1000,  # save the parameters after every saveFreq updates
          'sampleFreq':100,  # generate some samples after every sampleFreq updates
          'dataset':'flickr30k',
          'dictionary':None,  # word dictionary
          'use_dropout':False,  # setting this true turns on dropout at various points
          'use_dropout_lstm':False,  # dropout on lstm gates
          'reload_':True,
          'save_per_epoch':False}
params = cp.init_params(options)
for kk, pp in options.iteritems():
	params[kk] = options[kk]
tparams = OrderedDict()
print type(tparams)
for kk, pp in params.iteritems():
    tparams[kk] = theano.shared(params[kk], name=kk)
f = open('/home/f0z/feat/flickr30k/model.npz.pkl', 'wb')
c.dump(params, f)
```

**Comment by F0Z** [comment]
The issue is resolved by importing capgen inside the process.

**Comment by noureldien** [comment]
@F0Z Please, was you able to replicate the results of the paper using these hyperparameters on flickr_30k? How long (how many training epoch) did it take? Thank you.

**Comment by JunjieHu** [comment]
@F0Z  I have the same problem.  Can you describe more specifically where you import capgen?  I try import capgen at the beginning of the function gen_model() in the file of generate_caps.py.  But it doesn't resolve the problem.  Thanks
